<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Test Suite</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="assets/css/bootstrap.min.css" rel="stylesheet">
        <link href="assets/css/style.css" rel="stylesheet">
    </head>
    <body>
        <header>
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <ol class="breadcrumb">
                            <li class="active">Test Suite</li>

                            <?php
                            if (!$boolCoverage) {
                                echo '<li class="active"><a href="test.php?coverage=1">Coverage test</a></li>' . "\n<br>";
                            }
                            ?>

                        </ol>
                    </div>
                </div>
            </div>
        </header>

        <div class="container">

            <p>
                <?php wh('Time total: '); ?> <?php wh($numTimeTotal . ' sec.'); ?><br>
                <?php wh('Memory peak: ' . (memory_get_peak_usage(true) / 1024 / 1204) . " MB"); ?>
            </p>

            <?php
            if ($boolCoverage == true) {
                echo '<a href="coverage/" target="_blank">Coverage result</a>' . "\n<br><br>";
            }
            ?>

            <table class="table table-bordered">
                <thead>
                    <tr>
                        <td><div align="center"><strong>Test</strong></div></td>
                        <td><div align="center"><strong>Status</strong></div></td>
                        <td><div align="center"><strong>Message</strong></div></td>
                        <td><div align="center"><strong>Time</strong></div></td>
                        <td><div align="center"><strong>Memory</strong></div></td>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($arrTests as $arrTest) : ?>
                        <tr>
                            <td class="<?php wh($arrTest['class']); ?>"><?php wh($arrTest['name']); ?></td>
                            <td class="<?php wh($arrTest['class']); ?>">
                                <div class="progress">
                                    <div class="progress-bar progress-bar-<?php wh($arrTest['class']); ?>" role="progressbar" aria-valuenow="100.00" aria-valuemin="0" aria-valuemax="100" style="width: 100.00%">
                                        <span class="sr-only">(passed)</span>
                                    </div>
                                </div>
                            </td>
                            <td class="<?php wh($arrTest['class']); ?>"><div><?php wh($arrTest['message']); ?></div></td>
                            <td class="<?php wh($arrTest['class']); ?>"><div><?php wh($arrTest['time']); ?></div></td>
                            <td class="<?php wh($arrTest['class']); ?>"><div><?php echo $arrTest['memory_html']; ?></div></td>
                        </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
            <footer>
                <hr/>
                <h4>Legend</h4>
                <p>
                    <span class="success"><strong>passed</strong></span>
                    <span class="danger"><strong>failed</strong></span>
                    <span class="warning"><strong>skipped</strong></span>
                </p>
                <p>
                    <small>Generated by <a href="http://github.com/odan/molengo" target="_top">Molengo</a> TestSuite at <?php wh(date('d.m.Y h:i:s')); ?>
                    </small>
                </p>
            </footer>
        </div>
    </body>
</html>
